/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pers.zhc.android.def;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void abiFrom() {
        assertSame(AndroidAbi.from("x86_64"), AndroidAbi.X86_64);
        assertSame(AndroidAbi.from("ARM64-V8a"), AndroidAbi.ARM64_V8A);
        boolean failure = false;
        try {
            AndroidAbi.from("X862_64");
        } catch (Exception ignored) {
            failure = true;
        }
        assertTrue(failure);
    }
}
